on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for a full mirror

      - name: Mirror to GitLab
        env:
          # Use the secret you created in Step 2
          GITLAB_TOKEN: ${{ secrets.GITLAB_SECRET }}
        run: |
          # The URL for the GitLab repository, using the token for authentication
          GITLAB_URL="https://oauth2:${GITLAB_TOKEN}@gitlab.com/codedmoth/codedmoth.git"

          # Set up the remote for GitLab
          git remote add gitlab_mirror $GITLAB_URL

          # Push all branches and tags to the new remote
          git push --all gitlab_mirror --force
          git push --tags gitlab_mirror --force
